# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "GoogleReaderApiUniq"
  s.version = "0.3.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toon Willems", "Ivan Kasatenko"]
  s.date = "2012-06-05"
  s.description = "a google reader api (unofficial) written in ruby"
  s.email = "sky.31338@gmail.com"
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "GoogleReaderApiUniq.gemspec",
    "License",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "lib/google-reader-api-uniq/api.rb",
    "lib/google-reader-api-uniq/cache.rb",
    "lib/google-reader-api-uniq/entry.rb",
    "lib/google-reader-api-uniq/feed.rb",
    "lib/google-reader-api-uniq/google_login.rb",
    "lib/google-reader-api-uniq/rss_utils.rb",
    "lib/google-reader-api-uniq/subscription_list.rb",
    "lib/google-reader-api-uniq/user.rb",
    "lib/google_reader_api_uniq.rb"
  ]
  s.homepage = "http://github.com/SkyWriter/GoogleReaderAPI"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "a google reader api (unofficial) written in ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

